### ISSUE TITLE
add your plugin to PostHTML README and the Plugins Catalog

### ISSUE THREAD

**Issue by michael-ciniawsky** [canvaskisa/posthtml-modules#1]
Hi :) would you mind to send a PR to [posthtml](https:github.com/posthtml/posthtml) repo adding your plugin(s) and/or to the plugins [catalog](https://github.com/maltsev/posthtml-plugins) ?

**Comment by canvaskisa** [comment]
@michael-ciniawsky Hi, I'm really glad to do this, here is pull request for `posthtml-modules` :)

**Comment by canvaskisa** [comment]
@michael-ciniawsky And here is pull request with updated README for `posthtml` repo.

**Comment by canvaskisa** [comment]
Everything is merged.

**Comment by michael-ciniawsky** [comment]
Interested in @-rule-syntax support for posthtml-modules?

```html
<div>
  @module path/to/file.html
</div>
<div>
  @module file.html
</div>
```

**Comment by canvaskisa** [comment]
@michael-ciniawsky We can do it, but i don't think it's really necessary feature. it disables `<content></content>` directive inside modules, looks like just sugar for me. Basically i'm looking forward to implementing some kind of props passing to modules and support for relative paths, but for now, i don't really know how i'm going to implement this.

**Comment by michael-ciniawsky** [comment]
```<content></content> ```is use to merge existing and module content ? yeap right, it's just sugar and for consistant usage with e.g [posthtml-import](https://github.com/posthtml/posthtml-import). The general question is, if @-rule-syntax in html should be used at all. :)

When finding some free time a make a PR, just reject if you dislike it ;)

> Basically i'm looking forward to implementing some kind of props passing to modules 

by props you mean e.g something like this?

```html
<module href="file.html" plugins="bem exp" options="{bem: {}, exp: {}}"></module>
```

**Comment by michael-ciniawsky** [comment]
I made this plugin to [auto load posthtml config](https://github.com/posthtml/posthtml-load-config) from common sources e.g (package.json, posthtml.config.js, posthtmlrc.json), so for modules it should be possible to make it in a way like this. 

```txt
|––layout
|      |––module1
|      |        |––module1.html
|      |        |––posthtmlrc.json
|      |––module2
|               |––module2.html
|               |––posthtmlrc.json
|––index.html
|––package.json
```
```html
<body>
 <module href="module1.html" config="module1/posthtmlrc.json"></module>
 <module href="module2.html" config="module2/posthtmlrc.json"></module>
</body>
```

**Comment by canvaskisa** [comment]
@michael-ciniawsky Yeah `<content></content>` is exactly for that.
By props i meant something like this:
`index.html`
```html
<module href="module.html" value="test"></module>
```

`module.html`
```html
<div>
  <value></value>
</div>
```

`result.html`
```html
<div>
  test
</div>
```

**Comment by canvaskisa** [comment]
@michael-ciniawsky It's about passing props to module, render it or do something based on its value, like template languages, you know

**Comment by canvaskisa** [comment]
@michael-ciniawsky BTW i like your idea with custom config, i think its great and will be very happy if you send a PR 👍

**Comment by michael-ciniawsky** [comment]
context passing is a very nice idea 👍 

**index.html**
```html
<module href="file.html" content="file.json"></module>
```
**module.html**
```html
<div>
  <h1>`${title}`</h1>
  <p>`${text}`</p>
</div>
````

I don't want to stress you with various ideas, but i intend to build some kind of preprossecor (or template-engine) like preset on top of posthtml and posthtml-modules(precisely posthtml subprocesses for imported content) should be part of it. I wanted to build something similiar to poshtml-modules, but you were faster :).

**Comment by canvaskisa** [comment]
@michael-ciniawsky whoa! that's basically what i was thinking about  🙌
The story begins when i started to work with `react` and `css-modules` – i found that the concept `everything-in-js` is awesome, cause you can create encapsulated components with their own logic, styles and markup. But i faced the problem with some projects, when i cannot use `react` or it didn't make sense to use it, so i decided to implement some kind of component's encapsulation for simple markup, and accidentally found `posthtml` processor. I already finished some projects, based on several `poshtml` plugins, but it also uses `handlebars`, cause of tiny amount of `posthtml` plugins, so if you wish – i can share some code with you. I also would really like to implement something like template-engine, focused on modularity in html. ✨

**Comment by michael-ciniawsky** [comment]
:D :D :D it's nearly the same here.At the beginning I search for a SASS (libsass is written in C, always had bad luck when updating node and libsass broke etc.) replacement and took a look at PostCSS. awesome :+1. Then it it popped into my mind, that this should also work for markup related things. naively typed posthtml in the github searchbar, e violà :). Then react, css-modules and webpack hit the dev world and boosted my attemps even more. Before i looked at Polymer and Webcomponents in general, but i don't really like to have yet other lib in the project itself when not necessary(react is different here, its's very useful in SPA's, because of it's virtual-dom approach, tree diffing bli bla blub), but as you mentioned before it doesn't make sense in any context by default and especially on static sites will mostly be 90K LOC's of bloat in your code.
There shoud be a way to develop both, normal components and react components(especially functional stateless ones) out of one step and that's what i wanted to be build-in in the upcoming preprocessor :)

Currently i'm preparing and developing the posthtml plugins necessary.
Finally there should be replacements as plugins for replacing

Jade:

-posthtml-sml(Syntax),
-posthtml-import(Include),
-posthtml-extend(Extend, Prepend. Append), 
-posthtml-modules(Mixins and Components), 
-posthtml-inject(Assets and Assets Lazy Loaded)), 

Handlebars:
-posthtml-exp

> I already finished some projects, based on several poshtml plugins,
>  but it also uses handlebars, cause of tiny amount of posthtml plugins

Yes true, PostHTML ecosystem is not mature and broad like PostCSS's. Thats why i spend most of the time preparing and developing the posthtml plugins necessary at the moment, but that's also fun :).
Finally there should be at minium plugins for replacing

Jade:
-posthtml-sml(Syntax),
-posthtml-import(Include),
-posthtml-extend(Extend, Prepend. Append), 
-posthtml-modules(Mixins and Components), 
-posthtml-inject(Assets and Assets Lazy Loaded)), 

Handlebars:
-posthtml-exp

> so if you wish – i can share some code with you. 

yes 👍 that would be nice, please share want you can :)

> I also would really like to implement something like template-engine, focused on modularity in html.

Join us over at StandardHTML if you like :) ? I know the name is not that creative(subject to change), at the moment we wanted to make a guide of how to write proper markup and bundle posthtml plugins for doing that, it's also an attempt to make an Linter in the future. Modularity and react support is also 'planned'. We barely started at the moment every idea in general and how to join the various ways and methods in a sinful way are welcome. The result should be something like 

posthtml-(package)-html --> bundle of posthtml plugins for preprocessing modules and files (Jade + Handlebars replacement)
posthtml-standard --> bundle of posthtml plugins for ensuring best practices (order of attrs, no unnecessary tags ```<div><div><div>I' wrapped up</div></div></div>```, linting, w3c validity checks)

And to go even futher combine that with PostCSS 

postcss-(package)-css --> bundle of postcss plugins for preprocessing modules and files (SASS/LESS-like)
postcss-standard --> bundle of postcss plugins for ensuring best practices (order of attrs, no unsed css, linting, w3c validility check)

At the end of the day 'just'  ;) writting a sugar stack for modern webdev 

```txt
|––components
|    |––header
|    |    |––index.sml
|    |    |––index.sss
|    |    |––index.js
|    |––article
|           |––index.sml
|           |––index.sss
|           |––index.js
|–index.sss
|–index.sml / App.jsx (depends on react ? true : false)
|–package.json (posthtml: {} postcss: {}) or 
                                                                 //   |–posthtml.config.js
                                                                 //   |–postcss.config.js
|–webpack.config.js
```
There is more to it, just scratching the surface here, but its hard to express it in one post :). The hole madness comes from the intrinsic wish to get rid of all that yxz preprocessor combined with yxz others on each project and having no solid core were every dev can agree on and extend (via plugins) as they like or the usecase made necessary. That's subject to change...

**Comment by canvaskisa** [comment]
@michael-ciniawsky That's really awesome, i like your ideas a lot! 🙌

> Currently i'm preparing and developing the posthtml plugins necessary.
Finally there should be replacements as plugins for

Nice stuff, i will check out them, when i will have some time!

> Join us over at StandardHTML if you like :) ?

Yeah, i totally would like to :)

> bundle of posthtml plugins for preprocessing modules and files

That's what i have implemented for my side project. Here's a bare example of `posthtml` and `postcss` plugins i used for it:

```js
const postcss = require('posthtml-postcss-modules')({
  context: options.context,
  generateScopedName: process.env.NODE_ENV === 'production' ? '[hash:base64:5]' : '[path]__[local]__[hash:base64:5]',
  plugins: [
    require('postcss-import')({path: options.context}),
    require('postcss-short'),
    require('postcss-clearfix'),
    require('postcss-cssnext')
  ]
});

const plugins = [
  require('posthtml-extend')({root: options.context}),
  postcss,
  require('posthtml-modules')({
    context: options.context,
    plugins: [postcss]
  }),
  require('posthtml-remove-duplicates')('style'),
  require('posthtml-collect-styles')()
];

if (process.env.NODE_ENV === 'production') {
  plugins.push(require('posthtml-minifier')(minifier));
}
```

And my modular structure is like:
```sh
├── admin
│   └── index.html
├── error
│   └── index.html
├── fonts.css
├── layout.css
├── layout.html
├── main
│   ├── _
│   │   ├── header
│   │   │   ├── fixed.html
│   │   │   ├── root.html
│   │   │   └── simple.html
│   │   └── menu.html
│   ├── index.html
│   └── sections
│       ├── contacts.html
│       ├── preview
│       │   ├── index.css
│       │   └── index.html
│       ├── the-residence
│       │   ├── index.html
│       │   └── slider.html
│       └── the-site
│           ├── index.html
│           └── video.html
└── variables.css
```

And a simple module example:
```html
<style type="text/css" module>
  @import 'variables';

  .text {
    text: 25px 42px;
    width: calc(100% * (930 / var(--w-large)));
    margin-left: calc(100% * (495 / var(--w-large)));
    font-family: var(--serif);

    @media (--tablet-horizontal-only) {
      text: 15px 25px .5px;
      width: calc(100% * (580 / var(--w-normal)));
      margin-left: calc(100% * (350 / var(--w-normal)));
    }

    @media (--tablet-vertical-only) {
      margin-left: calc(100% * (140 / var(--w-medium)));
      width: calc(100% * (488 / var(--w-medium)));
      text: 13px 24px .5px;
    }

    @media (--mobile) {
      text: 11px 20px .3px;
      margin: 30px *;
      margin-left: calc(100% * (95 / var(--w-small)));
      width: calc(100% * (210 / var(--w-small)));
    }
  }
</style>

<p classname="text">{{text}}</p>
```

I would like to share more, but i have not finished that project, yet, and have a little time (i'm planning to finish it to the end of this week). I will try to do my best to share more with you ✊

For my future ideas i'd like to implement some kind of script processing with `babel`, `typescript` and others, just like `posthtml-postcss-modules`:
```html
<script type="text/javascript" type="babel">
</script>
```
Or something like that, but i don't really know how to scope it within an html file, need some thoughts about it.

Really love that someone have similar ideas like mine✨✨✨

**Comment by michael-ciniawsky** [comment]
> Yeah, i totally would like to :)

👍  I send an invite when i have time :)

> That's what i have implemented for my side project. Here's a bare example of posthtml and postcss plugins i used for it

👍  I looks nice, 

> For my future ideas i'd like to implement some kind of script processing with babel, typescript and others, just like posthtml-postcss-modules

A general extraxct/ tranform content plugin(s) would be nice e.g posthtml-ctx poshtml-extract
```txt
|–src
|   |–component.html
|–index.css
|–index.html
|–index.js
|–babelrc
|–posthtmlrc.json
|–postcssrc.json
```
```html
<style postcss="component.css">CSS here</style>
<template posthtml="component.html>HTML here</template>
<script babel="component.js">JS here</script>
```
**posthtml-ctx**
```js
require('posthtml-ctx)([
  {tag: 'style', postcss: () => {/* Set up postcss */},
  {tag: 'scrip't, babel: () => {/* Set up babel */},
]
```
```txt
|–src
|   |–component.html
|–dest
|   |–component.html
|   |–component.css
|   |–component.js
|–dest-reactify
|   |–component.css
|   |–component.jsx
|–index.css  (@import component.css)
|–index.html (@import component.html)
|–index.js (import component from 'component')
|–babelrc
|–posthtmlrc.json
|–postcssrc.json
```

Things like variables, custom properties, css-modules.json i18n.json etc.. should be configured in  common config file/folder where the various posthtml/postcss plugins can grab what the need. The tedious redundant plugin configuration is a ux problem in my opinion, there must be a way where the flexibilty of these tools not become a configuration hell that quickly.
